### ISSUE TITLE
Commit the log file and attempt to push it

### ISSUE THREAD

**Issue by katzuv** [Galaxia5987/log-downloader#9]

**Comment by rakrakon** [comment]
I don't think pushing is necessary, committing is enough. 
Also keep in mind that this will be mainly used in competitions where there is usually no internet.

**Comment by katzuv** [comment]
Remember how often we pushed in the competition and transferred files in the off-season? 🙃
There is no harm in trying to push. In the worst case it won't work.

**Comment by rakrakon** [comment]
c5411b9a54466f54dfeb723512d9e5f3038e7c6f

**Comment by katzuv** [comment]
Note that the same with threads, you shouldn't close issues by yourself. It is the author's job.
